# workflow name
name: Deploy to gh-pages & coding-pages

# master branch on push, auto run
on: 
  workflow_dispatch:
  repository_dispatch:
    types: [opened, start]
  push:
    branches:
      - master
      
jobs:
  build: 
    runs-on: ubuntu-latest 
        
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
      - name: 拉取代码
        uses: actions/checkout@v2
        with:
          ref: master
          persist-credentials: false
        
      # from: https://github.com/actions/setup-node  
      - name: 安装 Node.js 10.x 
        uses: actions/setup-node@master
        with:
          node-version: "10.x"
      
      - name: 安装 Hexo 依赖
        run: |
          npm install hexo-cli -g
          npm install
      
      - name: 设置 Private Key
        env:
          HEXO_DEPLOY_PRIVATE_KEY: ${{ secrets.HEXO_DEPLOY_PRIVATE_KEY }}
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRIVATE_KEY" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan e.coding.net >> ~/.ssh/known_hosts
          git config --global user.name '$GIT_USER_NAME' 
          git config --global user.email '$GIT_USER_EMAIL'
          
      - name: Deploy Hexo 
        run: |
          hexo clean
          hexo generate 
          hexo deploy